# Generated by Django 5.2.3 on 2025-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="دخل اسم الفئة",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الفئة",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_name_ar",
                    models.CharField(
                        help_text="دخل اسم الدولة باللغة العربية",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الدولة",
                    ),
                ),
                (
                    "country_name_en",
                    models.CharField(
                        help_text="دخل اسم الدولة باللغة الإنجليزية",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["country_name_ar"],
            },
        ),
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(max_length=100, verbose_name="اسم الموقع"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, verbose_name="البريد الإلكتروني للتواصل"
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(max_length=20, verbose_name="رقم الدعم"),
                ),
                (
                    "whatsapp_number",
                    models.CharField(max_length=20, verbose_name="رقم الواتساب"),
                ),
                (
                    "tiktok_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط لينكد إن"
                    ),
                ),
                ("facebook_url", models.URLField(verbose_name="رابط فيسبوك")),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط تويتر"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط إنستجرام"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط يوتيوب"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="project_info/logos/",
                        verbose_name="شعار الموقع",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="project_info/favicons/",
                        verbose_name="أيقونة الموقع",
                    ),
                ),
                ("description", models.TextField(verbose_name="وصف الموقع")),
                (
                    "places",
                    models.TextField(
                        help_text="قائمة بأسماء أماكن فروعنا",
                        verbose_name="أماكن فروعنا",
                    ),
                ),
                ("vision", models.TextField(verbose_name="رؤية الموقع")),
                ("mission", models.TextField(verbose_name="رسالة الموقع")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
            ],
            options={
                "verbose_name": "Information Project",
            },
        ),
        migrations.CreateModel(
            name="TruckType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="دخل اسم الشاحنة",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الشاحنة",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
