# Generated by Django 5.2.3 on 2025-07-10 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="دحل اسم المنتج/العرض",
                        max_length=70,
                        unique=True,
                        verbose_name="اسم المنتج/العرض",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="دخل وصف المنتج/العرض",
                        verbose_name="وصف المنتج/العرض",
                    ),
                ),
                ("slug", models.SlugField(max_length=70, unique=True)),
                (
                    "is_item_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذا المنتج/عرض نشط؟ يعني تريد ات يظهر فالصفحة لليوزر",
                        verbose_name="يظهر لليور؟",
                    ),
                ),
                (
                    "discount_rate_type",
                    models.CharField(
                        choices=[("percent", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        default="fixed",
                        help_text="اختار نوع العملية الحسابية الذي ستطبق علي سعر العرض",
                        max_length=10,
                    ),
                ),
                (
                    "discount_rate_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="دخل قيمة معدل الخصم لسعر العرض",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اختر المنتجات التي تريد تضمينها في هذا العرض",
                        null=True,
                        related_name="offers",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OfferImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="اختر صورة للمنتج",
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="رتب هذه الصورة لعرضها في الترتيب الصحيح"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        help_text="اختر العرض الذي تريد ربط هذه الصورة به",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="offers.offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Image",
                "verbose_name_plural": "Offer Images",
                "ordering": ["order", "id"],
            },
        ),
    ]
