# Generated by Django 5.2.3 on 2025-08-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="governorate",
            name="uuid",
        ),
    ]
