# Generated by Django 5.2.3 on 2025-07-10 07:51

import django.core.validators
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("offers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_name",
                    models.CharField(
                        help_text="دخل اسم العميل",
                        max_length=100,
                        verbose_name="اسم العميل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="دخل ايميل العميل",
                        max_length=254,
                        verbose_name="ايميل العميل",
                    ),
                ),
                ("address", models.TextField(verbose_name="عنوان العميل بالتفصيل")),
                (
                    "order_number",
                    models.CharField(
                        default=orders.models.generate_order_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "فانتظار تأكيد الطلب من العميل"),
                            ("processing", "يتم تجهيز الطلبية"),
                            ("delivered", "تم التوصيل"),
                            ("cansaled", "تم الغاء الطلب"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="تتبع تسليم الطلب",
                    ),
                ),
                (
                    "type_deliver",
                    models.CharField(
                        choices=[
                            ("home", "توصيل عادي"),
                            ("pickup", "توصيل سريع"),
                            ("self", "استلام من المتجر"),
                        ],
                        default="home",
                        max_length=20,
                        verbose_name="طريقة توصيل الطلب؟",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="سجل اي ملاحظات متعلقة بالطلب",
                        null=True,
                        verbose_name="ملاحظات عن الطلب",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.city",
                        verbose_name="المدينة اللي ساكن فيها العميل",
                    ),
                ),
                (
                    "government",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.governorate",
                        verbose_name="المحافظة اللي ساكن فيها العميل",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="offers.offer",
                        verbose_name="العرض اللي العميل  طلبه",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="المنتج اللي العميل طلبه",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
