# Generated by Django 5.2.3 on 2025-08-11 17:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="دحل اسم المنتج/العرض",
                        max_length=70,
                        unique=True,
                        verbose_name="اسم المنتج/العرض",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="دخل وصف المنتج/العرض",
                        verbose_name="وصف المنتج/العرض",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_item_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذا المنتج/عرض نشط؟ يعني تريد ات يظهر فالصفحة لليوزر",
                        verbose_name="يظهر لليور؟",
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="دخل سعر الجملة",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="سعر الجملة",
                    ),
                ),
                (
                    "market_price_increase_type",
                    models.CharField(
                        choices=[("percent", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        default="fixed",
                        help_text="اختار نوع العملية الحسابية الذي ستطبق علي سعر الجملة",
                        max_length=10,
                    ),
                ),
                (
                    "market_price_increase_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="دخل قيمة معدل الزيادة لسعر الجملة",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "market_price",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="سعر المنتج فالسوق"
                    ),
                ),
                (
                    "is_item_new",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذا المنتج جديد؟ يعني تريد ات يظهر فالصفحة لليوزر فجزء وصلنا حديثا",
                        verbose_name="هل المنتج جديد فالسوق؟",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="دخل الفئات التي ينتمي إليها هذا المنتج",
                        related_name="products",
                        to="core.category",
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True,
                        help_text="دخل الدول التي اتصنع منها هذا المتتج",
                        related_name="products",
                        to="core.country",
                    ),
                ),
                (
                    "truck",
                    models.ManyToManyField(
                        blank=True,
                        help_text="دحل الشاحنات التي يتناسب معها هذا المنتج",
                        related_name="products",
                        to="core.trucktype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        default="fixed",
                        help_text="Select the type of discount",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the discount value",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no start date", null=True
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no end date", null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Is this discount currently active?"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="اختر صورة للمنتج",
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="رتب هذه الصورة لعرضها في الترتيب الصحيح"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["order", "id"],
            },
        ),
    ]
